### ISSUE TITLE
Bug: ActivityBar在dev模式下无法正常适应低分辨率

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/webui#190]
#### 配置：默认（console开启devMode)

随意开一个Console（默认模板也行），使用默认配置保持console::devMode开启，使用yarn dev运行
多开几个console plugin，让Activity Icon 多一点，随后缩放网页令ActivityBar空间不足，可以拖来拖去放大放小玩一会
（也可以不缩放，先让网页处于低分辨率下，比如我测试屏幕2k，令网页在1/4角落状态下打开Console亦可）
#### 此时控制台报错：

```
vue-router.mjs:3030 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'path' in undefined
    at Object.resolve (vue-router.mjs:3030:13)
    at ReactiveEffect.fn (vue-router.mjs:2169:41)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at useLink (vue-router.mjs:2212:30)
    at setup (vue-router.mjs:2258:31)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
Show 89 more frames
runtime-core.esm-bundler.js:7438 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'exposed')
    at getExposeProxy (runtime-core.esm-bundler.js:7438:16)
    at setRef (runtime-core.esm-bundler.js:4419:42)
    at unmount (runtime-core.esm-bundler.js:6182:7)
    at unmountChildren (runtime-core.esm-bundler.js:6314:7)
    at unmount (runtime-core.esm-bundler.js:6215:9)
    at unmountComponent (runtime-core.esm-bundler.js:6294:7)
    at unmount (runtime-core.esm-bundler.js:6195:7)
    at unmountComponent (runtime-core.esm-bundler.js:6294:7)
    at unmount (runtime-core.esm-bundler.js:6195:7)
    at unmountChildren (runtime-core.esm-bundler.js:6314:7)
Show 35 more frames
runtime-core.esm-bundler.js:988 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (runtime-core.esm-bundler.js:988:27)
    at updateComponent (runtime-core.esm-bundler.js:5628:9)
    at processComponent (runtime-core.esm-bundler.js:5576:7)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at patchBlockChildren (runtime-core.esm-bundler.js:5427:7)
    at patchElement (runtime-core.esm-bundler.js:5319:7)
    at processElement (runtime-core.esm-bundler.js:5167:7)
    at patch (runtime-core.esm-bundler.js:5028:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5773:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
Show 25 more frames
````
#### ActivityBar现状（已经放大回2k）：
![image](https://github.com/koishijs/webui/assets/16983883/0827c78b-3faf-4cc6-83e5-d2830b18d338)

#### 影响：
在从低分状态放大回正常分辨率后，尽管ActivityBar呈现以上状态，但对自带插件影响较小，但我自己的插件由于在Component中使用store作为绑定，在这一过程后绑定无法触发。
除刷新外无法解除此状态。
在低分状态下，大部分插件无法使用（所有插件的左侧边栏点击无反应，上标题栏右侧按钮无反应等）
![image](https://github.com/koishijs/webui/assets/16983883/a6c9bc15-77ac-4e38-a13e-5b422a54d7a1)

关闭devMode则没有此问题

环境：Koishi 4.13.3 & Console 5.11.3

**Comment by shigma** [comment]
如果刷新能解决的话就不是大问题?

**Comment by Hieuzest** [comment]
确实不是什么大问题，只要开发时尽可能保持网页高度足够+关闭不需要的Activity就可以规避

提一下是一方面虽然影响不大，但毕竟是非预期行为，可能有我不了解的更底层的原因
另一方面今天群里有一位遇到的问题非常像本issue，我判断为其本身屏幕分辨率过低导致
