### ISSUE TITLE
Bug: plugin-analytics 当用户默认授权等级为0时 用户执行指令会报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#269]
感觉应该是授权等级 0 然后没有生成用户 导致没有 userId 导致的
```node
2023-12-18 17:40:30 [W] mysql > INSERT INTO `analytics.command` (`date`, `hour`, `name`, `selfId`, `userId`, `channelId`, `platform`, `count`) VALUES (19709, 17, 'unbind', '3099360661', NULL, '976331649', 'onebot', 1) ON DUPLICATE KEY UPDATE `count` = (ifnull(`count`, 0) + 1)
2023-12-18 17:40:30 [W] app ER_BAD_NULL_ERROR: Column 'userId' cannot be null
                            at _MySQLDriver.query (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:434:19)
                            at _MySQLDriver.upsert (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:604:31)
                            at _Executable.execute (/koishi/node_modules/@minatojs/core/lib/index.cjs:456:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.upsert (/koishi/node_modules/@minatojs/core/lib/index.cjs:670:12)
                            at async Proxy.uploadAudit (/koishi/node_modules/@koishijs/plugin-analytics/lib/index.js:124:5)
                            at async Promise.all (index 1)
                            at async Proxy.upload (/koishi/node_modules/@koishijs/plugin-analytics/lib/index.js:136:7)

```

**Comment by ilharp** [comment]
看起来可以检测一下 `userId`，如果用户不存在，那么也不应当计入统计数据
