### ISSUE TITLE
bug: 停用分组后 操作分组内的插件 会报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#280]
复现方式
1. 新建分组
2. 分组内添加插件
3. 停用分组
4. 启用或停用分组内的插件

错误日志
```
loader TypeError: Cannot read properties of undefined (reading 'ctx')
                            at Proxy.unload (/home/project/TSWorkSpace/koishi/development/koishi-dev/node_modules/@koishijs/plugin-config/src/shared/writer.ts:153:30)
                            at _Client.ctx.console.addListener.authority (/home/project/TSWorkSpace/koishi/development/koishi-dev/node_modules/@koishijs/plugin-config/src/shared/writer.ts:59:27)
                            at WebSocket.receive (/home/project/TSWorkSpace/koishi/development/koishi-dev/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/src/client.ts:35:45)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

分组停用后 应该禁止操作分组内的插件 只允许修改配置

**Comment by CyanChanges** [comment]
![image](https://github.com/koishijs/webui/assets/68551684/1cd2f922-4054-4387-aaed-e7d373b41705)
复现了, 但是我这个复现方式这种情况在正常使用的时候不会用到(  
当 manager/unload config 是空 Object (`{}`) 的时候就炸了 
用这个 `koishi-plugin-expose-ctx` 就可以拿到 @koishijs/client 的 send as sendClient 了(
