### ISSUE TITLE
property console.config is not registered, declare it as `inject` to suppress this warning

### ISSUE THREAD

**Issue by UlyssesZh** [koishijs/webui#325]
```
Error: property console.config is not registered, declare it as `inject` to suppress this warning
at checkInject (/koishi/node_modules/@cordisjs/core/lib/index.cjs:807:38)
at Object.get (/koishi/node_modules/@cordisjs/core/lib/index.cjs:817:11)
at Object.get (/koishi/node_modules/@cordisjs/core/lib/index.cjs:845:22)
at Reflect.get (<anonymous>)
at Object.get (/koishi/node_modules/@cordisjs/core/lib/index.cjs:244:22)
at Proxy.getFiles (/koishi/node_modules/@koishijs/plugin-console/lib/node/index.js:120:15)
at Proxy.resolveEntry (/koishi/node_modules/@koishijs/plugin-console/lib/node/index.js:129:59)
at /koishi/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:235:19
at /koishi/node_modules/cosmokit/lib/index.cjs:78:80
at Array.map (<anonymous>)
```

**Comment by shigma** [comment]
此问题应该仅存在于旧版本中。请更新全部依赖到最新版本，或删除 lockfile 后重新安装。

**Comment by UlyssesZh** [comment]
我在更新全部插件后触发了这个问题. 已经靠重新部署解决.
